service: website-backend

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: cards/create.create
    events:
      - http:
          path: cards
          method: post
          cors: true

  list:
    handler: cards/list.list
    events:
      - http:
          path: cards
          method: get
          cors: true

  get:
    handler: cards/get.get
    events:
      - http:
          path: cards/{id}
          method: get
          cors: true

  update:
    handler: cards/update.update
    events:
      - http:
          path: cards/{id}
          method: put
          cors: true

  delete:
    handler: cards/delete.delete
    events:
      - http:
          path: cards/{id}
          method: delete
          cors: true
  
  createUser:
    handler: users/createUser.createUser
    events:
      - http:
          path: users
          method: post
          cors: true

resources:
  Resources:
    CardsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}